[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "assemblyai-transcribe"
version = "0.1.0a1"
description = "Small CLI for uploading local audio to AssemblyAI and printing transcripts."
readme = "README.md"
requires-python = ">=2"
license = "MIT"
authors = [
  { name = "Jifeng Wu", email = "jifengwu2k@gmail.com" }
]
classifiers = [
  "Programming Language :: Python :: 2",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "typing; python_version < '3.5'"
]

[project.scripts]
assemblyai_transcribe = "assemblyai_transcribe:main"

[project.urls]
Homepage = "https://github.com/jifengwu2k/assemblyai_transcribe"
"Bug Tracker" = "https://github.com/jifengwu2k/assemblyai_transcribe/issues"
